baseurl = "/"
languageCode = "en-us"
title = "GetEnvoy"
theme = "getenvoy"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
pygmentsUseClasses = true
pluralizelisttitles = false

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Get Envoy"
	description = "Simplify your service mesh data plane."

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = ""
		# The icons will be shown if you enter your username
		twitter = "GetEnvoyProxy"
		github = "tetratelabs/getenvoy"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Tetrate.io"
		]


	[params.about]
		hide  = false
		logo = "GetEnvoy"
		title = "The easiest way to get started with Envoy"
		subtitle = "on any cloud or platform"
		version = "0.0.1"
		envoyVersion = "1.11.1"

		[[ params.about.cta ]]
			title = "Get Started"
			href = "/platforms/"

    [params.platforms]
        hide  = false

    [params.releases]
        hide = true

    [params.startnow]
        hide = false

    [params.subscribe]
        hide = true

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.rss]
		hide  = true
